<p>My last post caused quite a stir in the Rust subreddit lol. Luckily, it's not a hill I am willing to die on. The post was more about having fun, poking holes on some annoyance I face while programming in Rust every day, than truly throwing hate to something or someone. I mean, who would plaster memes on a subject they are 100% serious about, right?</p>

<img src="https://www.rismosch.com/articles/an-even-better-error-type/wojak.webp" style="display: block; margin: auto; max-width: 100%;">

<p>Nonetheless, I did get some value out of it. A single commenter pointed out that actually, Rust does have a utility to capture the stack trace. Well, it isn't built into <code class="code">Result</code>, and you still need to call the function manually, but it exists. And poof. My biggest argument against <code class="code">Result</code> just evaporated.</p>

<p>Capturing the stack trace allows for some beautiful ergonomics: Calling <code class="code">file!()</code> and <code class="code">line!()</code> isn't as important anymore, as all information is on the stack trace anyway. This means, no macro for conversion between errors is necessary, and now it actually makes sense to implement a generic <code class="code">From</code>, that converts <i>every</i> <code class="code">std::error::Error</code> into a <code class="code">RisError</code>. Sure, it adds one more frame to the stack, but who cares? The entire thing is captured anyway <span style="display: inline-block">&#175;&#92;&#95;&#40;&#12484;&#41;&#95;&#47;&#175;</span></p>

<p>I find it quite silly that so many people recommended to just use some crate. Especially since the entire implementation, plus some utility, fits into a little over 100 lines of code. Again, it was just a single person who realized the actual problem. I am really getting <a href="https://www.npmjs.com/package/is-odd" target="_blank" rel="noopener noreferrer">is-odd</a> vibes from this situation.</p>

<p>Enough condescending talk about redditors. Here's the new, better <code class="code">RisError</code>:</p>

<p><a href="https://github.com/Rismosch/ris_engine/blob/7829aada888eae6a11378605824f1d6cae40dd6e/crates/ris_error/src/error.rs" target="_blank" rel="noopener noreferrer">GitHub permalink</a></p>

<code class="code code_block">
<span style="color:var(--pico-8-cyan)">use</span> <span style="color:var(--pico-8-washed-grey)">std</span>::<span style="color:var(--pico-8-washed-grey)">backtrace</span>::<span style="color:var(--pico-8-washed-grey)">Backtrace</span>;<br>
<span style="color:var(--pico-8-cyan)">use</span> <span style="color:var(--pico-8-washed-grey)">std</span>::<span style="color:var(--pico-8-washed-grey)">error</span>::<span style="color:var(--pico-8-washed-grey)">Error</span>;<br>
<span style="color:var(--pico-8-cyan)">use</span> <span style="color:var(--pico-8-washed-grey)">std</span>::<span style="color:var(--pico-8-washed-grey)">sync</span>::<span style="color:var(--pico-8-washed-grey)">Arc</span>;<br>
<br>
<span style="color:var(--pico-8-cyan)">pub type</span> <span style="color:var(--pico-8-washed-grey)">SourceError</span> = <span style="color:var(--pico-8-washed-grey)">Option</span>&lt;<span style="color:var(--pico-8-washed-grey)">Arc</span>&lt;<span style="color:var(--pico-8-cyan)">dyn</span> <span style="color:var(--pico-8-washed-grey)">Error</span> + <span style="color:var(--pico-8-cyan)">'static</span>&gt;&gt;;<br>
<span style="color:var(--pico-8-cyan)">pub type</span> <span style="color:var(--pico-8-washed-grey)">RisResult</span>&lt;<span style="color:var(--pico-8-washed-grey)">T</span>&gt; = <span style="color:var(--pico-8-washed-grey)">Result</span>&lt;<span style="color:var(--pico-8-washed-grey)">T</span>, <span style="color:var(--pico-8-washed-grey)">RisError</span>&gt;;<br>
<br>
#<span style="color:var(--pico-8-cyan)">[</span><span style="color:var(--pico-8-brown)">derive</span><span style="color:var(--pico-8-washed-grey)"><span style="color:var(--pico-8-green)">(</span>Clone<span style="color:var(--pico-8-green)">)</span></span><span style="color:var(--pico-8-cyan)">]</span><br>
<span style="color:var(--pico-8-cyan)">pub struct</span> <span style="color:var(--pico-8-washed-grey)">RisError</span> <span style="color:var(--pico-8-cyan)">{</span><br>
&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:var(--pico-8-cyan)">pub</span> source: <span style="color:var(--pico-8-washed-grey)">SourceError</span>,<br>
&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:var(--pico-8-cyan)">pub</span> message: <span style="color:var(--pico-8-washed-grey)">Option</span>&lt;<span style="color:var(--pico-8-washed-grey)">String</span>&gt;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:var(--pico-8-cyan)">pub</span> file: <span style="color:var(--pico-8-washed-grey)">String</span>,<br>
&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:var(--pico-8-cyan)">pub</span> line: <span style="color:var(--pico-8-washed-grey)">u32</span>,<br>
&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:var(--pico-8-cyan)">pub</span> backtrace: <span style="color:var(--pico-8-washed-grey)">Arc</span>&lt;<span style="color:var(--pico-8-washed-grey)">Backtrace</span>&gt;,<br>
<span style="color:var(--pico-8-cyan)">}</span><br>
<br>
<span style="color:var(--pico-8-cyan)">impl</span> <span style="color:var(--pico-8-washed-grey)">std</span>::<span style="color:var(--pico-8-washed-grey)">fmt</span>::<span style="color:var(--pico-8-washed-grey)">Display</span> <span style="color:var(--pico-8-cyan)">for</span> <span style="color:var(--pico-8-washed-grey)">RisError</span> <span style="color:var(--pico-8-cyan)">{</span><br>
&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:var(--pico-8-cyan)">fn</span> <span style="color:var(--pico-8-brown)">fmt</span>(&<span style="color:var(--pico-8-cyan)">self</span>, <u>f</u>: &<span style="color:var(--pico-8-cyan)">mut</span> <span style="color:var(--pico-8-washed-grey)">std</span>::<span style="color:var(--pico-8-washed-grey)">fmt</span>::<span style="color:var(--pico-8-washed-grey)">Formatter</span>&lt;<span style="color:var(--pico-8-cyan)">'_</span>&gt;<span style="color:var(--pico-8-green)">)</span> -&gt; <span style="color:var(--pico-8-washed-grey)">std</span>::<span style="color:var(--pico-8-washed-grey)">fmt</span>::<span style="color:var(--pico-8-washed-grey)">Result</span> <span style="color:var(--pico-8-green)">{</span><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:var(--pico-8-pink)">if</span> <span style="color:var(--pico-8-cyan)">let</span> <span style="color:var(--pico-8-washed-grey)">Some</span><span style="color:var(--pico-8-brown)">(</span>source<span style="color:var(--pico-8-brown)">)</span> = &<span style="color:var(--pico-8-cyan)">self</span>.source <span style="color:var(--pico-8-brown)">{</span><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:var(--pico-8-cyan)">write!(</span><u>f</u>, <span style="color:var(--pico-8-brown)">"<span style="color:var(--pico-8-cyan)">{}</span>"</span>, source<span style="color:var(--pico-8-cyan)">)</span>?;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:var(--pico-8-brown)">}</span><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:var(--pico-8-pink)">if</span> <span style="color:var(--pico-8-cyan)">let</span> <span style="color:var(--pico-8-washed-grey)">Some</span><span style="color:var(--pico-8-brown)">(</span>message<span style="color:var(--pico-8-brown)">)</span> = &<span style="color:var(--pico-8-cyan)">self</span>.message <span style="color:var(--pico-8-brown)">{</span><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:var(--pico-8-cyan)">write!(</span><u>f</u>, <span style="color:var(--pico-8-brown)">"</span><span style="color:var(--pico-8-red)">\n</span>&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:var(--pico-8-brown)">message:</span> <span style="color:var(--pico-8-red)">\"</span><span style="color:var(--pico-8-cyan)">{}</span><span style="color:var(--pico-8-red)">\"</span><span style="color:var(--pico-8-brown)">"</span>, message<span style="color:var(--pico-8-cyan)">)</span>?;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:var(--pico-8-brown)">}</span><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:var(--pico-8-cyan)">write!</span><span style="color:var(--pico-8-brown)">(</span><u>f</u>, <span style="color:var(--pico-8-brown)">"</span><span style="color:var(--pico-8-red)">\n</span>&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:var(--pico-8-brown)">at</span> <span style="color:var(--pico-8-cyan)">{}</span>:<span style="color:var(--pico-8-cyan)">{}</span><span style="color:var(--pico-8-brown)">"</span>, <span style="color:var(--pico-8-cyan)">self</span>.file, <span style="color:var(--pico-8-cyan)">self</span>.line<span style="color:var(--pico-8-brown)">)</span><br>
&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:var(--pico-8-green)">}</span><br>
<span style="color:var(--pico-8-cyan)">}</span><br>
<br>
<span style="color:var(--pico-8-cyan)">impl</span> <span style="color:var(--pico-8-washed-grey)">std</span>::<span style="color:var(--pico-8-washed-grey)">fmt</span>::<span style="color:var(--pico-8-washed-grey)">Debug</span> <span style="color:var(--pico-8-cyan)">for</span> <span style="color:var(--pico-8-washed-grey)">RisError</span> <span style="color:var(--pico-8-cyan)">{</span><br>
&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:var(--pico-8-cyan)">fn</span> <span style="color:var(--pico-8-brown)">fmt</span><span style="color:var(--pico-8-green)">(</span>&<span style="color:var(--pico-8-cyan)">self</span>, <u>f</u>: &<span style="color:var(--pico-8-washed-grey)">mut</span> <span style="color:var(--pico-8-washed-grey)">std</span>::<span style="color:var(--pico-8-washed-grey)">fmt</span>::<span style="color:var(--pico-8-washed-grey)">Formatter</span>&lt;<span style="color:var(--pico-8-cyan)">'_</span>&gt<span style="color:var(--pico-8-green)">)</span> -&gt; <span style="color:var(--pico-8-washed-grey)">std</span>::<span style="color:var(--pico-8-washed-grey)">fmt</span>::<span style="color:var(--pico-8-washed-grey)">Result</span> <span style="color:var(--pico-8-green)">{</span><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:var(--pico-8-cyan)">write!</span><span style="color:var(--pico-8-brown)">(</span><u>f</u>, <span style="color:var(--pico-8-brown)">"</span><span style="color:var(--pico-8-cyan)">{}</span><span style="color:var(--pico-8-red)">\n</span><span style="color:var(--pico-8-brown)">backtrace:</span><span style="color:var(--pico-8-red)">\n</span><span style="color:var(--pico-8-cyan)">{}</span><span style="color:var(--pico-8-brown)">"</span>, <span style="color:var(--pico-8-cyan)">self</span>, <span style="color:var(--pico-8-cyan)">self</span>.backtrace<span style="color:var(--pico-8-brown)">)</span><br>
&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:var(--pico-8-green)">}</span><br>
<span style="color:var(--pico-8-cyan)">}</span><br>
<br>
#<span style="color:var(--pico-8-cyan)">[</span><span style="color:var(--pico-8-brown)">derive</span><span style="color:var(--pico-8-washed-grey)">(Debug)</span><span style="color:var(--pico-8-cyan)">]</span><br>
<span style="color:var(--pico-8-cyan)">pub struct</span> <span style="color:var(--pico-8-washed-grey)">OptionError</span>;<br>
<br>
<span style="color:var(--pico-8-cyan)">impl</span> <span style="color:var(--pico-8-washed-grey)">Error</span> <span style="color:var(--pico-8-cyan)">for</span> <span style="color:var(--pico-8-washed-grey)">OptionError</span> <span style="color:var(--pico-8-cyan)">{}</span><br>
<br>
<span style="color:var(--pico-8-cyan)">impl</span> <span style="color:var(--pico-8-washed-grey)">std</span>::<span style="color:var(--pico-8-washed-grey)">fmt</span>::<span style="color:var(--pico-8-washed-grey)">Display</span> <span style="color:var(--pico-8-cyan)">for</span> <span style="color:var(--pico-8-washed-grey)">OptionError</span> <span style="color:var(--pico-8-cyan)">{</span><br>
&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:var(--pico-8-cyan)">fn</span> <span style="color:var(--pico-8-brown)">fmt</span><span style="color:var(--pico-8-green)">(</span>&<span style="color:var(--pico-8-washed-grey)">self</span>, <u>f</u>: &<span style="color:var(--pico-8-cyan)">mut</span> <span style="color:var(--pico-8-washed-grey)">std</span>::<span style="color:var(--pico-8-washed-grey)">fmt</span>::<span style="color:var(--pico-8-washed-grey)">Formatter</span>&lt;<span style="color:var(--pico-8-cyan)">'_</span>&gt<span style="color:var(--pico-8-green)">)</span> -&gt; <span style="color:var(--pico-8-washed-grey)">std</span>::<span style="color:var(--pico-8-washed-grey)">fmt</span>::<span style="color:var(--pico-8-washed-grey)">Result</span> <span style="color:var(--pico-8-green)">{</span><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:var(--pico-8-cyan)">write!</span><span style="color:var(--pico-8-brown)">(</span><u>f</u>, <span style="color:var(--pico-8-brown)">"Option was None")</span><br>
&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:var(--pico-8-green)">}</span><br>
<span style="color:var(--pico-8-cyan)">}</span><br>
<br>
<span style="color:var(--pico-8-cyan)">impl</span>&lt;<span style="color:var(--pico-8-washed-grey)">E</span>: <span style="color:var(--pico-8-washed-grey)">Error</span> + <span style="color:var(--pico-8-cyan)">'static</span>&gt <span style="color:var(--pico-8-washed-grey)">From</span>&lt;<span style="color:var(--pico-8-washed-grey)">E</span>&gt; <span style="color:var(--pico-8-cyan)">for</span> <span style="color:var(--pico-8-washed-grey)">RisError</span> <span style="color:var(--pico-8-cyan)">{</span><br>
&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:var(--pico-8-cyan)">fn</span> <span style="color:var(--pico-8-brown)">from</span><span style="color:var(--pico-8-green)">(</span>value: <span style="color:var(--pico-8-washed-grey)">E</span><span style="color:var(--pico-8-green)">)</span> -&gt; <span style="color:var(--pico-8-cyan)">Self</span> <span style="color:var(--pico-8-green)">{</span><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:var(--pico-8-cyan)">Self</span> <span style="color:var(--pico-8-brown)">{</span><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;source: <span style="color:var(--pico-8-washed-grey)">Some</span><span style="color:var(--pico-8-cyan)">(</span><span style="color:var(--pico-8-washed-grey)">Arc</span>::<span style="color:var(--pico-8-brown)">new</span><span style="color:var(--pico-8-green)">(</span>value<span style="color:var(--pico-8-green)">)</span><span style="color:var(--pico-8-cyan)">)</span>,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;message: <span style="color:var(--pico-8-washed-grey)">None</span>,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;file: <span style="color:var(--pico-8-washed-grey)">String</span>::<span style="color:var(--pico-8-brown)">from</span><span style="color:var(--pico-8-cyan)">(file!</span><span style="color:var(--pico-8-green)">()</span><span style="color:var(--pico-8-cyan)">)</span>,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;line: <span style="color:var(--pico-8-cyan)">line!()</span>,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;backtrace: <span style="color:var(--pico-8-cyan)">crate</span>::<span style="color:var(--pico-8-cyan)">get_backtrace!()</span>,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:var(--pico-8-brown)">}</span><br>
&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:var(--pico-8-green)">}</span><br>
<span style="color:var(--pico-8-cyan)">}</span><br>
<br>
<span style="color:var(--pico-8-cyan)">pub trait</span> <span style="color:var(--pico-8-washed-grey)">Extensions</span>&lt;<span style="color:var(--pico-8-washed-grey)">T</span>&gt; <span style="color:var(--pico-8-cyan)">{</span><br>
&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:var(--pico-8-cyan)">fn</span> <span style="color:var(--pico-8-brown)">unroll</span><span style="color:var(--pico-8-green)">(</span><span style="color:var(--pico-8-cyan)">self</span><span style="color:var(--pico-8-green)">)</span> -&gt; <span style="color:var(--pico-8-washed-grey)">Result</span>&lt;<span style="color:var(--pico-8-washed-grey)">T</span>, <span style="color:var(--pico-8-washed-grey)">RisError</span>&gt;;<br>
<span style="color:var(--pico-8-cyan)">}</span><br>
<br>
<span style="color:var(--pico-8-cyan)">impl</span>&lt;<span style="color:var(--pico-8-washed-grey)">T</span>&gt; <span style="color:var(--pico-8-washed-grey)">Extensions</span>&lt;<span style="color:var(--pico-8-washed-grey)">T</span>&gt; <span style="color:var(--pico-8-cyan)">for</span> <span style="color:var(--pico-8-washed-grey)">Option</span>&lt;<span style="color:var(--pico-8-washed-grey)">T</span>&gt; <span style="color:var(--pico-8-cyan)">{</span><br>
&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:var(--pico-8-cyan)">fn</span> <span style="color:var(--pico-8-brown)">unroll</span><span style="color:var(--pico-8-green)">(</span><span style="color:var(--pico-8-cyan)">self</span><span style="color:var(--pico-8-green)">)</span> -&gt; <span style="color:var(--pico-8-washed-grey)">Result</span>&lt;<span style="color:var(--pico-8-washed-grey)">T</span>, <span style="color:var(--pico-8-washed-grey)">RisError</span>&gt; <span style="color:var(--pico-8-green)">{</span><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:var(--pico-8-pink)">match</span> <span style="color:var(--pico-8-cyan)">self</span> <span style="color:var(--pico-8-brown)">{</span><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:var(--pico-8-washed-grey)">Some</span><span style="color:var(--pico-8-cyan)">(</span>value<span style="color:var(--pico-8-cyan)">)</span> =&gt; <span style="color:var(--pico-8-washed-grey)">Ok</span><span style="color:var(--pico-8-cyan)">(</span>value<span style="color:var(--pico-8-cyan)">)</span>,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:var(--pico-8-washed-grey)">None</span> =&gt; <span style="color:var(--pico-8-washed-grey)">Err</span><span style="color:var(--pico-8-cyan)">(</span><span style="color:var(--pico-8-washed-grey)">RisError</span>::<span style="color:var(--pico-8-brown)">from</span><span style="color:var(--pico-8-green)">(</span><span style="color:var(--pico-8-washed-grey)">OptionError</span><span style="color:var(--pico-8-green)">)</span><span style="color:var(--pico-8-cyan)">)</span>,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:var(--pico-8-brown)">}</span><br>
&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:var(--pico-8-green)">}</span><br>
<span style="color:var(--pico-8-cyan)">}</span><br>
<br>
#<span style="color:var(--pico-8-cyan)">[</span>macro_export<span style="color:var(--pico-8-cyan)">]</span><br>
<span style="color:var(--pico-8-cyan)">macro_rules! new {</span><br>
&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:var(--pico-8-green)">(</span>$<span style="color:var(--pico-8-brown)">(</span>$arg:tt<span style="color:var(--pico-8-brown)">)</span>*<span style="color:var(--pico-8-green)">)</span> =&gt; <span style="color:var(--pico-8-green)">{</span><span style="color:var(--pico-8-brown)">{</span><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:var(--pico-8-cyan)">use</span> $<span style="color:var(--pico-8-cyan)">crate</span>::<span style="color:var(--pico-8-washed-grey)">error</span>::<span style="color:var(--pico-8-washed-grey)">RisError</span>;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:var(--pico-8-cyan)">let</span> source = <span style="color:var(--pico-8-washed-grey)">None</span>;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:var(--pico-8-cyan)">let</span> message = <span style="color:var(--pico-8-washed-grey)">Some</span><span style="color:var(--pico-8-cyan)">(</span><span style="color:var(--pico-8-brown)">format!</span><span style="color:var(--pico-8-green)">(</span>$<span style="color:var(--pico-8-brown)">(</span>$arg<span style="color:var(--pico-8-brown)">)</span>*<span style="color:var(--pico-8-green)">)</span><span style="color:var(--pico-8-cyan)">)</span>;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:var(--pico-8-cyan)">let</span> file = <span style="color:var(--pico-8-washed-grey)">String</span>::<span style="color:var(--pico-8-brown)">from</span><span style="color:var(--pico-8-cyan)">(</span><span style="color:var(--pico-8-brown)">file!</span><span style="color:var(--pico-8-green)">()</span><span style="color:var(--pico-8-cyan)">)</span>;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:var(--pico-8-cyan)">let</span> line = <span style="color:var(--pico-8-brown)">line!</span><span style="color:var(--pico-8-cyan)">()</span>;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:var(--pico-8-cyan)">let</span> backtrace = $<span style="color:var(--pico-8-cyan)">crate</span>::<span style="color:var(--pico-8-brown)">get_backtrace!</span><span style="color:var(--pico-8-cyan)">()</span>;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:var(--pico-8-washed-grey)">RisError</span><span style="color:var(--pico-8-cyan)">{</span>source, message, file, line, backtrace<span style="color:var(--pico-8-cyan)">}</span><br>
&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:var(--pico-8-brown)">}</span><span style="color:var(--pico-8-green)">}</span>;<br>
<span style="color:var(--pico-8-cyan)">}</span><br>
<br>
#<span style="color:var(--pico-8-cyan)">[</span>macro_export<span style="color:var(--pico-8-cyan)">]</span><br>
<span style="color:var(--pico-8-cyan)">macro_rules! new_result {</span><br>
&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:var(--pico-8-green)">(</span>$<span style="color:var(--pico-8-brown)">(</span>$arg:tt<span style="color:var(--pico-8-brown)">)</span>*<span style="color:var(--pico-8-green)">)</span> =&gt; <span style="color:var(--pico-8-green)">{</span><span style="color:var(--pico-8-brown)">{</span><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:var(--pico-8-cyan)">let</span> result = $<span style="color:var(--pico-8-cyan)">crate</span>::<span style="color:var(--pico-8-brown)">new!</span><span style="color:var(--pico-8-cyan)">(</span>$<span style="color:var(--pico-8-green)">(</span>$arg<span style="color:var(--pico-8-green)">)</span>*<span style="color:var(--pico-8-cyan)">)</span>;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:var(--pico-8-washed-grey)">Err</span><span style="color:var(--pico-8-cyan)">(</span>result<span style="color:var(--pico-8-cyan)">)</span><br>
&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:var(--pico-8-brown)">}</span><span style="color:var(--pico-8-green)">}</span>;<br>
<span style="color:var(--pico-8-cyan)">}</span><br>
<br>
#<span style="color:var(--pico-8-cyan)">[</span>macro_export<span style="color:var(--pico-8-cyan)">]</span><br>
<span style="color:var(--pico-8-cyan)">macro_rules! get_backtrace {</span><br>
&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:var(--pico-8-green)">()</span> =&gt; <span style="color:var(--pico-8-green)">{</span><span style="color:var(--pico-8-brown)">{</span><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:var(--pico-8-cyan)">use</span> <span style="color:var(--pico-8-washed-grey)">std</span>::<span style="color:var(--pico-8-washed-grey)">backtrace</span>::<span style="color:var(--pico-8-washed-grey)">Backtrace</span>;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:var(--pico-8-cyan)">use</span> <span style="color:var(--pico-8-washed-grey)">std</span>::<span style="color:var(--pico-8-washed-grey)">sync</span>::<span style="color:var(--pico-8-washed-grey)">Arc</span>;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:var(--pico-8-cyan)">let</span> backtrace = <span style="color:var(--pico-8-washed-grey)">Arc</span>::<span style="color:var(--pico-8-brown)">new</span><span style="color:var(--pico-8-cyan)">(</span><span style="color:var(--pico-8-washed-grey)">Backtrace</span>::<span style="color:var(--pico-8-brown)">force_capture</span><span style="color:var(--pico-8-green)">()</span><span style="color:var(--pico-8-cyan)">)</span></span>;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:var(--pico-8-brown)">eprintln!</span><span style="color:var(--pico-8-cyan)">(</span><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:var(--pico-8-brown)">"<span style="color:var(--pico-8-red)">\u{001B}</span>[93mWARNING<span style="color:var(--pico-8-red)">\u{001B}</span>[0m: created backtrace. this operation is expensive. excessive use may cost performance.<span style="color:var(--pico-8-red)">\n</span>&nbsp;&nbsp;&nbsp;&nbsp;in {}:{}<span style="color:var(--pico-8-red)">\n</span><span style="color:var(--pico-8-brown)">"</span>,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:var(--pico-8-brown)">file!</span><span style="color:var(--pico-8-green)">()</span>,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:var(--pico-8-brown)">line!</span><span style="color:var(--pico-8-green)">()</span>,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:var(--pico-8-cyan)">)</span>;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;backtrace<br>
&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:var(--pico-8-brown)">}</span><span style="color:var(--pico-8-green)">}</span><br>
<span style="color:var(--pico-8-cyan)">}</span><br>
</code>
